FROM ubuntu:16.04

# 将源更换一下，速度更快。
ADD ./sources.list /etc/apt/

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils wget openssh-server openssh-client git zsh tree python3 python3-pip \
    && pip3 install numpy pandas scipy sklearn xgboost -i https://pypi.douban.com/simple/ \
    && rm -rf /var/lib/apt/lists/* && apt-get clean \
    && rm -rf ~/.cache/pip/

# oh-my-zsh 并且更为 zsh 风格 ys，将zsh替代默认的bash。
RUN git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh \
    && cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc \
    && cp ~/.zshrc ~/.zshrc.orig \
    && chsh -s /bin/zsh \
    && sed -ri 's/^ZSH_THEME="robbyrussell"/ZSH_THEME="ys"/' /root/.zshrc
