FROM ubuntu:16.04

# 将源更换一下，速度更快。
ADD ./sources.list /etc/apt/
RUN mkdir ~/.pip
ADD ./pip.conf ~/.pip/

# 其中，安装的 pytorch 中，适用于 cuda8。
# 其中，需要安装 git 然后下载 caffe，再删除 git。
RUN apt-get update && apt-get upgrade -y \
    # 安装 python3 环境。
    && apt-get install -y apt-utils wget python3-dev python3-pip \
    # 安装科学计算库。
    && pip3 install sklearn numpy pandas ipython matplotlib -i https://pypi.douban.com/simple/ \
    # 安装 pytorch。
    && pip3 install torch torchvision -i https://pypi.douban.com/simple/ \
    # 安装 tensorflow，CPU+GPU。
    && pip3 install tensorflow tensorflow-gpu -i https://pypi.douban.com/simple/ \
    # 安装 caffe。
    && apt-get install -y libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler \
    && apt-get install -y --no-install-recommends libboost-all-dev \
    && apt-get install -y libopenblas-dev liblapack-dev libatlas-base-dev \
    && apt-get install -y libgflags-dev libgoogle-glog-dev liblmdb-dev \
    && apt-get install -y git cmake build-essential \
    && git clone https://github.com/BVLC/caffe.git \
    # 删除一些不再使用的东西，保证镜像购销。
    && apt-get uninstall git \
    && rm -rf /var/lib/apt/lists/* && apt autoremove && apt-get clean \
    && rm -rf ~/.cache/pip/
