FROM ubuntu:16.04

# 将源更换一下，速度更快。
ADD ./sources.list /etc/apt/

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y apt-utils curl wget openjdk-8-jdk scala python3 python3-pip && rm -rf /var/lib/apt/lists/*

# 这里最好不要升级pip3，有bug，以及，下载包时，换源增加下载速度。
RUN pip3 install numpy scipy pandas matplotlib -i https://pypi.douban.com/simple/

# 删除pip3的缓存。
RUN rm -rf ~/.cache/pip

ENV JAVA_HOME=/usr/java/jdk1.8.0_131
ENV PATH $JAVA_HOME/bin:$PATH
