FROM ubuntu:16.04

# 将源更换一下，速度更快。
ADD ./sources.list /etc/apt/

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y apt-utils wget && rm -rf /var/lib/apt/lists/*

# 这里最好不要升级pip3，有bug，以及，下载包时，换源增加下载速度。
# RUN pip3 install numpy scipy pandas matplotlib -i https://pypi.douban.com/simple/

# 删除pip3的缓存。
# RUN rm -rf ~/.cache/pip

# ENV JAVA_HOME=/usr/java/jdk1.8.0_131
# ENV PATH $JAVA_HOME/bin:$PATH

RUN  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz \
    && tar -zxvf /jdk-8u172-linux-x64.tar.gz -C /usr/local/ \
    && mv /usr/local/jdk1.8.0_172 /usr/local/jdk1.8 \
    && rm /jdk-8u172-linux-x64.tar.gz

RUN wget https://downloads.lightbend.com/scala/2.11.4/scala-2.11.4.tgz \
    && tar -zxvf /scala-2.11.4.tgz -C /usr/local/ \
    && mv /usr/local/scala-2.11.4 /usr/local/scala \
    && rm /scala-2.11.4.tgz
